#!/usr/bin/env bash

set -e

branches=(preprod prod)
prefixes=(PREPROD PROD)

# If there's an argument, it's the PR message. Else, the message is the last commit message
[ -z "$1" ] && msg=$(git log -1 --pretty=%B)
[ -z "$msg" ] && msg=$1

# Initialize useful vars
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Coloriables
git fetch --all
i=0;
while [ $i -lt ${#branches[@]} ]; do
    messages[i]="[${prefixes[i]}] $msg"
    remotes[i]="origin/${branches[i]}"
    i=$[$i+1]
done
head=$(git rev-parse --abbrev-ref HEAD)

# Print summary and ask confirmation
i=0;
while [ $i -lt ${#branches[@]} ]; do
    echo -e "${GREEN}${messages[i]}${NC} -> ${RED}${remotes[i]}${NC}"
    while read -r line; do
        echo "    $line"
    done <<< "$(git log --color --left-right --graph --cherry-pick --oneline $head...${remotes[i]} | tac)"
    i=$[$i+1]
done
echo
read -p "Create ${#branches[@]} pull requests? "

# Open pull requests
i=0;
while [ $i -lt ${#branches[@]} ]; do
    echo -n "[${prefixes[i]}]: "
    hub pull-request -m "${messages[i]}" -b ${branches[i]} -h $head
    i=$[$i+1]
done

