#!/usr/bin/env bash

set -e

setUpBeforeTestSuite() {
    export GIT_PRETTY_PR_TEST="true"  
    export EDITOR=$suiteDir/fake_editor.sh
    testDir=/tmp/git-pretty-pull-request/
    [ -e $testDir ] && rm -rf $testDir
    cp -r $suiteDir $testDir
    cd $testDir
    git config pretty-pull-request.pull-bases "preprod prod"
    setup_mocks
}

tearDownAfterTestSuite() {
    rm -rf $testDir
}

setup_mocks() {
    for mock in $suiteDir/tests/mocks/*.sh; do
        . $mock
    done
}

suiteDir=$(cd $(dirname $0) && pwd)

#########################################
# Main
#########################################

setUpBeforeTestSuite

bats $suiteDir/tests

tearDownAfterTestSuite

